apiVersion: v1
kind: Secret
metadata:
  name: gerrit-wui-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.env.DB_USER | quote }}
  DB_PASS: {{ .Values.env.DB_PASS | quote }}
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  GERRIT_TOKEN: {{ .Values.env.GERRIT_TOKEN | quote }}
  GERRIT_URL: {{ .Values.env.GERRIT_URL | quote }}
  GERRIT_USER: {{ .Values.env.GERRIT_USER | quote }}
  SERVER_PORT: {{ .Values.env.SERVER_PORT | quote }}
  BOARDS: {{ .Values.env.BOARDS | quote }}
  DESCRIPTION_QA: {{ .Values.env.DESCRIPTION_QA | quote }}
  QUERY_QA: {{ .Values.env.QUERY_QA | quote }}
  CUSTOM_FIELD_NAME_QA: {{ .Values.env.CUSTOM_FIELD_NAME_QA | quote }}
  CUSTOM_FIELD_VALUE_QA: {{ .Values.env.CUSTOM_FIELD_VALUE_QA | quote }}
  DEFAULT_QUERY: {{ .Values.env.DEFAULT_QUERY | quote }}
